version: '3'
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    scale: 3  # Add this for docker-compose compatibility

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi_app